import type { Config } from 'tailwindcss'

const config: Config = {
  content: ['./src/**/*.{ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        brand: {
          50:  'var(--brand-50)',
          100: 'var(--brand-100)',
          200: 'var(--brand-200)',
          300: 'var(--brand-300)',
          400: 'var(--brand-400)',
          500: 'var(--brand-500)',
          600: 'var(--brand-600)',
          700: 'var(--brand-700)',
          800: 'var(--brand-800)',
          900: 'var(--brand-900)',
        },
        secondary: {
          50:  'var(--secondary-50)',
          100: 'var(--secondary-100)',
          200: 'var(--secondary-200)',
          300: 'var(--secondary-300)',
          400: 'var(--secondary-400)',
          500: 'var(--secondary-500)',
          600: 'var(--secondary-600)',
          700: 'var(--secondary-700)',
          800: 'var(--secondary-800)',
          900: 'var(--secondary-900)',
        },
        accent: {
          50:  'var(--accent-50)',
          100: 'var(--accent-100)',
          200: 'var(--accent-200)',
          300: 'var(--accent-300)',
          400: 'var(--accent-400)',
          500: 'var(--accent-500)',
          600: 'var(--accent-600)',
          700: 'var(--accent-700)',
          800: 'var(--accent-800)',
          900: 'var(--accent-900)',
        },
        neutral: {
          50:  'var(--neutral-50)',
          100: 'var(--neutral-100)',
          200: 'var(--neutral-200)',
          300: 'var(--neutral-300)',
          400: 'var(--neutral-400)',
          500: 'var(--neutral-500)',
          600: 'var(--neutral-600)',
          700: 'var(--neutral-700)',
          800: 'var(--neutral-800)',
          900: 'var(--neutral-900)',
        },
        surface: {
          DEFAULT:   'var(--surface)',
          secondary: 'var(--surface-secondary)',
          tertiary:  'var(--surface-tertiary)',
          overlay:   'var(--surface-overlay)',
          glass:     'var(--surface-glass)',
        },
        border: {
          DEFAULT:   'var(--border)',
          secondary: 'var(--border-secondary)',
          subtle:    'var(--border-subtle)',
          strong:    'var(--border-strong)',
          focus:     'var(--border-focus)',
        },
        text: {
          primary:   'var(--text-primary)',
          secondary: 'var(--text-secondary)',
          tertiary:  'var(--text-tertiary)',
          inverse:   'var(--text-inverse)',
          link:      'var(--text-link)',
        },
        status: {
          success:       'var(--status-success)',
          'success-50':  'var(--status-success-50)',
          'success-700': 'var(--status-success-700)',
          warning:       'var(--status-warning)',
          'warning-50':  'var(--status-warning-50)',
          'warning-700': 'var(--status-warning-700)',
          error:         'var(--status-error)',
          'error-50':    'var(--status-error-50)',
          'error-700':   'var(--status-error-700)',
          info:          'var(--status-info)',
          'info-50':     'var(--status-info-50)',
          'info-700':    'var(--status-info-700)',
        },
      },
      fontFamily: {
        sans: ['var(--font-sans)'],
        mono: ['var(--font-mono)'],
      },
      fontSize: {
        xs:    'var(--text-xs)',
        sm:    'var(--text-sm)',
        base:  'var(--text-base)',
        lg:    'var(--text-lg)',
        xl:    'var(--text-xl)',
        '2xl': 'var(--text-2xl)',
        '3xl': 'var(--text-3xl)',
        '4xl': 'var(--text-4xl)',
      },
      borderRadius: {
        DEFAULT: 'var(--radius)',
        sm:   'var(--radius-sm)',
        lg:   'var(--radius-lg)',
        xl:   'var(--radius-xl)',
        full: 'var(--radius-full)',
      },
      boxShadow: {
        xs:       'var(--shadow-xs)',
        card:     'var(--shadow-card)',
        dropdown: 'var(--shadow-dropdown)',
        lg:       'var(--shadow-lg)',
        modal:    'var(--shadow-modal)',
        glass:    'var(--shadow-glass)',
      },
      transitionDuration: {
        fast:   '150ms',
        normal: '250ms',
        slow:   '350ms',
      },
      zIndex: {
        dropdown: '100',
        sticky:   '200',
        overlay:  '300',
        modal:    '400',
        toast:    '500',
      },
    },
  },
  plugins: [],
}

export default config
